---
format:
  revealjs:
    css: custom.css
    footer: "Taylor | ECON 0150 | Week 2 | Class B"
    transition: none
---

## ECON 0150 | Economic Data Analysis {.center}
<p class="subheader-center">How economists analyze data.</p>

---

## Part 1.1 | Categorical Variables
<p class="subheader">Three main variable types</p>

**Binary**: two categories (yes/no; true/false)

- *Employment Status (Employed, Unemployed)*

**Nominal**: no inherent order
  
- *Employment Sector (Agriculture, Services, Unemployed).*

**Ordinal**: meaningful order without consistent interval.
  
- *Economic Optimism (Very Pessimistic to Very Optimistic).*

---

## Part 1.1 | Binary Categorical
<p class="subheader">Exercise: summarize binary_categorical_dataset.csv</p>

---

## Part 1.1 | Nominal Categorical
<p class="subheader">Exercise: Summarize nominal_categorical_dataset.csv</p>

. . .

<br><br><br>

The main difference from Binary: more categories!

---

## Part 1.1 | Ordinal Categorical
<p class="subheader">Exercise: Summarize ordinal_categorical_dataset.csv</p>

. . .

<br><br><br>

The main difference from Ordinal: order the axis!

---

## Part 1.2 | Numerical Variable
<p class="subheader">Two main variable types</p>

**Discrete**: countable numbers with meaningful intervals

- *Number of Children in a Household.*

**Continuous**: quantities measurable on the reals.

- *Household Income in USD.*

---

## Part 1.2 | Discrete Numerical
<p class="subheader">Exercise: Summarize discrete_numerical_dataset.csv</p>

. . .

<br><br><br>

- Very similar to Ordinal Categorical.
- Statistical summaries can matter.
---

## Part 1.2 | Continuous Numerical
<p class="subheader">Exercise: Summarize continuous_numerical_dataset.csv</p>

. . .

<br><br><br>

- Very similar to Discrete Numerical.
- Other types of visualizations: Histograms, Boxplots, Jittered Scatters.

---

## Part 1.2 | Data Structures
<p class="subheader">...relationships between data points.</p>

| | Cross-Sectional | Time-Series | Panel Data |
|-|----|---|----|
| **Focus** | Multiple units, one time point | One unit, many times | Multiple units, many time points |
| **Shape** | Wide format | Long format | Long format |
| **Ex.** | Household income, 2025 | US GDP,   10 years | Household income, 10 years |

---

## Part 1.2 | Cross-Sec. Numerical
<p class="subheader">Exercise: Summarize cross_sectional_numerical_dataset.csv</p>

. . .

<br><br><br>

- Use visualizations of the distribution like Histograms, Boxplots, Jittered Scatters.

---

## Part 1.2 | Time-Series Numerical
<p class="subheader">Exercise: Summarize time_series_numerical_dataset.csv</p>

. . .

<br><br><br>

- Use visualizations of the distribution like Histograms, Boxplots, Jittered Scatters.
- Link data through time using a Linegraph.

---

## Part 1.2 | Panel Numerical
<p class="subheader">Exercise: Summarize panel_numerical_dataset.csv</p>

---











