---
format:
  revealjs:
    css: custom.css
    transition: none
    aspect-ratio: "16:9"
---

## ECON 0150 | Economic Data Analysis {.center}
<p class="subheader">The economist's data analysis pipeline.</p>

<br> 

### *Part 3.1 | Sampling*

---

## Sampling Outline
1. we will only ever see a sample of a population. even with the census, we're taking a sample - no way to know every possible census we could have taken, there's still variability in the way the world could go
2. the sample is a subset (repeated draws) of the population
3. the population follows a distribution
4. this is what we call a random varible: we draw an observation from a distribution
5. a sample is just repeated observations from a distribution
6. if we know the distribution, our life is simple
7. in practice we NEVER know the distribution
8. so what do we do? how would we answer the question: is the average age in pittsburgh greater than 45? can we answer it without asking everyone and without knowing the true distribution of ages?
9. yes. lets run a simulation. i have an unknown distribution. lets take repeated samples. 
10. we can look at the distribution of one sample, show the mean, and compare it to 45. 
11. what happens if we do this a bunch of times? well sometimes we get True and sometimes we get False. so which is it?
12. well, how comfortable are we being wrong? like, with the question at hand and the data, it looks like sometimes my guess correct and sometimes its not. 
13. we can be less wrong if we increase the sample size - if i do repeated samples, i can see that i'm less wrong - so if I draw once, i'm going to be wrong with a lower probability
14. so the distribution of sample means has some known properties.
15. it turns out we know exactly THIS distribution - do a bit of derivation of the CLT
16. then show that the CLT estimate gives the same conclusion as doing a bunch of sampling
17. it's mathematically identical to move the confidence interval from the truth to the sample mean, and show that we draw the same conclusions
18. so we don't even need to know anything about the underlying population? thats right! this is the most unhearalded idea in modern science. we can say so much while starting with so little.
19. then do a t-test using regression, connecting the p-value to the number of times we got the wrong answer
20. there are lots of other ways to do (or explain) this, but they all mean the same thing: sample means follow the t-distribution no matter the underlying distribution