
- Last time we found the best-fitting line
- But what does the slope actually tell us?
- Take education and wages example
- Slope is $2000 per year of education
- Does this mean everyone gets exactly $2000 more?
- Obviously not - we saw the scatter
- Think about what the line represents
- For each year of education, what's the typical increase?
- Like moving one year right, how far up do we go?
- Some people go up more, some less
- But look closer at the scatter
- Variation seems bigger for higher education
- PhD wages vary more than high school wages
- This is called heteroskedasticity
- "Hetero" = different, "skedastic" = spread
- Let's simulate this pattern
- Generate data where spread increases with x
- Our usual standard errors assume constant spread
- But that's wrong here!
- Like using the wrong ruler to measure uncertainty
- Need to adjust for changing spread
- Let's simulate to see what happens if we don't
- Draw wrong conclusions about relationships
- Especially bad with multiple variables
- This is why we need robust standard errors
- Like letting our ruler stretch with the spread
- Then we can trust our confidence intervals again
- And our hypothesis tests
- Next time: how do we handle multiple variables?

- Last time we saw education wasn't the whole story
- Wages depend on experience too
- And industry, location, gender, race...
- Could make separate regressions for each
- But we'd miss how they work together
- And run out of data quickly
- Let's think about adjusting one thing at a time
- Take out experience effect first
- Then look at education pattern in adjusted data
- Or could take out education first
- Then look at experience pattern
- Get different answers this way!
- What's going on?
- Education and experience are related
- More education usually means less experience
- We need to adjust for both at once
- But how do we find the "best" adjustment?
- Same idea as before - minimize mistakes
- Just with more dimensions
- Let's simulate with two variables
- Generate data where we know true relationships
- Look at patterns one at a time vs together
- Multiple regression gives each variable's effect
- "Holding others constant"
- Or "all else equal"
- Like isolating each relationship
- Each coefficient has its own standard error
- Can test each one like before
- But also test them together
- Are education AND experience related to wages?
- This is what we call an F-test
- Just like ANOVA but with continuous variables
- Next time: what can go wrong?
