---
title: "Welcome"
format:
  revealjs:
    transition: none
    theme: simple
    slide-number: true
jupyter: python3
---


This is a Jupyter Notebook. It contains both text cells (like this one) and code cells. Jupyter Notebooks are interactive - you can make changes or add cells, and then run a cell to see its output. Just select a cell and click the run cell button above in the toolbar ( ▶ Run ) or enter `Ctrl`+`Enter` (Windows) or `Commmand`+`Return` (Mac) from the keyboard.

To learn more about Jupyter Notebooks, see the [Jupyter documentation](https://jupyter-notebook.readthedocs.io/).


# Formatted Text

Create formatted text in Markdown cells to provide a description of your analysis - choose the cell type "Markdown" from the selector above in the toolbar. To edit any cell, double click on it - to render the output text, run the cell.

You can make text *italic* or **bold** or ***both italic and bold***.

You can create block quotes

> Facts are stubborn things, but statistics are pliable.
>
> \- *Mark Twain*

Create bulleted and numbered lists
- Apples
- Oranges
- Grapes

1. Wake up
2. Get out of bed
3. Drag a comb across my head

To learn more about Markdown, see the [Markdown Syntax documentation](https://jupyter-notebook.readthedocs.io/).

# Python Code

Embed Python code chunks in your notebook - choose the cell type "Code" from the selector above in the toolbar. Like markdown cells, you run the cell to see its output - give it a try!

```{python}
# Code cell ready to be run...
import time, sys
for i in range(10):
    print(i)
    time.sleep(0.5)
```

# Installing packages

## Using pip
To install a package with pip from a notebook use the [magic syntax](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip). This will ensure the package is installed into the correct kernel. Although this method is the most foolproof, the pip install statement will run every time the entire notebook is executed which may be undesirable.
```
%pip install pandas
```

To install a package with pip from a terminal, make sure to reference the same python version as the kernel in which the package will be used. For example, if the desired kernel is python 3.9.5:
```
python-3.9.5 -m pip install pandas
```

To list packages installed for a specific kernel:
```
python-3.9.5 -m pip list
```

## Using conda
To install packages with conda, first create a conda environment and register it as a kernel. From a terminal:
```
conda create --name test_env
# agree to the prompt
conda activate test_env
```

When the environment is activated the command line prompt should show the environment name `(test_env) /cloud/project$`. Next install `ipykernel` and register the environment as a kernel so it can be used from a notebook:
```
conda install ipykernel
python -m ipykernel install --user --name=test_env
```

> Note: pre-installed python versions should not be used once a conda environment is activated. Simply use `python` to correctly reference the python version in the environment.

Once the kernel is registered it will appear as an option in the "New" menu. To install a conda package from within a notebook, use the [magic syntax](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-conda).
```
%conda install pandas
```

To install a conda package from the terminal, ensure the environment is activated then:
```
conda install pandas
```

## Using venv
It is also possible to create a virtual environment and register it as a kernel. From a terminal:
```
python-3.9.5 -m venv test
# activate the environment
cd test
source bin/activate
```

Before installing packages, it's necessary to create a pip configuration file to override the user settings for the virtual env. The file must be in the top level directory for the venv. In this example `/cloud/project/test`. Use `vi` or from the jupyter tree view select "New" -> "Text File". Name the file `pip.conf` and add the following to its contents:
```
[install]
    user=false
[list]
    user=false
```

Now pip can be used normally whenever the venv is activated:
```
pip install jsondiff
pip list
```

To use a virtual environment as a notebook kernel, with the environment activated:
```
pip install ipykernel
python -m ipykernel install --user --name=test
```

# Using R in Notebooks
If you want to use R in your Jupyter notebook, you will need to install an R kernel like [IR Kernel](https://irkernel.github.io).  

## Install the IR kernel
1. Start a new terminal by clicking on `File > Open` menu item, then select `New > Terminal` from the drop down on the right hand side.
2. Lanuch an R terminal by typing the following (this example uses R version `4.3.1`, but you can use any other version installed in `/opt/R`):
```
/opt/R/4.3.1/bin/R
```
3. Install the `IRkernel` package (answer `yes` when prompted to create your own personal package library):
```
install.packages('IRkernel')
```
4. Select the CRAN mirror to install from.  This will kickoff the `IRKernel` installation which could take several minutes.
5. After `IRkernel` is installed, run the following command to make the kernel available to Jupyter:
```
IRkernel::installspec()
```
6. Restart the notebook server to pickup the new R kernel by clicking on `Control Panel`, `Stop My Server`, then `Start My Server`

## Using the R kernel
At this point, you should have a new R kernel available for creating new notebooks. To create a notebook with the R kernel, click on the `New` dropdown and select the `R` kernel option.

To install R packages in your R notebook (for example, `ggplot2`), type the following in a notebook cell:
```
install.packages('ggplot2') 
```

To run your R code, type it in a notebook cell.  For example:
```
library(ggplot2)
ggplot(midwest, aes(x=area, y=poptotal)) + geom_point()
```

